[package]
name = "enquirer"
version = "0.3.1"
authors = ["Pavan Kumar Sunkara <pavan.sss1991@gmail.com>"]
edition = "2018"
description = "Command Line Utility for Stylish Interactive Prompts"
categories = ["command-line-utilities", "development-tools"]
repository = "https://github.com/termapps/enquirer"
readme = "README.md"
license = "MIT"
include = ["src/**/*.rs", "Cargo.toml", "LICENSE", "*.md"]

[badges]
travis-ci = { repository = "termapps/enquirer" }
maintenance = { status = "actively-developed" }

[dependencies]
dialoguer = "0.5.1"
structopt = "0.3.7"
console = "0.10.1"

[[bin]]
name = "enquirer"
path = "src/main.rs"

[lib]
name = "enquirer"
path = "src/lib.rs"
doctest = false
